### ISSUE TITLE
alg: include weighted costs in the optimization function

### ISSUE THREAD

**Issue by armfazh** [mmcloughlin/addchain#117]
addchain optimizes for the minimum of M+S.
However, this assumes the cost of M and S are equal.

It's common the rate S/M varies depending on the field.

```
| Example | S=M | S=0.8M | S=0.6 M | 
| 3M + 2S | 5.0 |  5.6   |  4.2    |
| 4M + 1S | 5.0 |  4.8   |  4.6    |
```

The feature request is allow the user to specify the cost of operations.

**Comment by mmcloughlin** [comment]
Just landed #120, which is just about the simplest thing I could do to support this. Let me know what you think.
