### ISSUE TITLE
results: NIST P-256 Field Inversion is out of date

### ISSUE THREAD

**Issue by josharian** [mmcloughlin/addchain#131]
Playing around, I ran NIST P-256 Field Inversion. The results page (and readme) says the best known cost is 266:

But a local run of addchain says 264. :)

```
addchain: expr: "2^256-2^224+2^192+2^96-1"
addchain: hex: ffffffff00000001000000000000000000000000ffffffffffffffffffffffff
addchain: dec: 115792089210356248762697446949407573530086143415290314195533631308867097853951
addchain: best: opt(dictionary(sliding_window(32),continued_fractions(dichotomic)))
addchain: cost: 264
_10       = 2*1
_11       = 1 + _10
_1100     = _11 << 2
_1111     = _11 + _1100
_11110000 = _1111 << 4
_11111111 = _1111 + _11110000
x16       = _11111111 << 8 + _11111111
x32       = x16 << 16 + x16
i230      = ((x32 << 32 + 1) << 128 + x32) << 32
return      (x32 + i230) << 32 + x32
```

I wonder how many other "best knowns" you've now bested. :)

**Comment by mmcloughlin** [comment]
I wish this were the case but unfortunately for field inversion we need a chain for `p-2` not `p`, as you have there. Actually sometimes there's a reason to use `p-3` instead, which is the case for P-256, as explained here: https://briansmith.org/ecc-inversion-addition-chains-01#p256_field_inversion.

This required delta (2 or 3) is listed on the results page as the `d` parameter:

https://github.com/mmcloughlin/addchain/blob/master/doc/results.md#nist-p-256-field-inversion

I have setup a rube goldbergian code generation scheme in this repository, so it should not be possible for the results page to get out of date. It's produced by this template:

https://github.com/mmcloughlin/addchain/blob/fa760c82056fc4f0f961b650563a6a75f9cd54ce/internal/tools/docgen/templates/results.tmpl

which is populated from this package:

https://github.com/mmcloughlin/addchain/blob/fa760c82056fc4f0f961b650563a6a75f9cd54ce/internal/results/results.go#L63-L66

And the tests in that package verify that the chain is still the shortest for that case. It's regenerated by `script/generate`:

https://github.com/mmcloughlin/addchain/blob/fa760c82056fc4f0f961b650563a6a75f9cd54ce/script/generate#L25

And if it gets out of date CI would fail:

https://github.com/mmcloughlin/addchain/blob/fa760c82056fc4f0f961b650563a6a75f9cd54ce/.github/workflows/ci.yml#L60-L65

**Comment by mmcloughlin** [comment]
Closing because I think this was answered. Let me know if you had any more questions.
